menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/verifycode
    Download: 

favicon: https://avatars1.githubusercontent.com/u/29533708?v=3&s=460
logo: https://avatars1.githubusercontent.com/u/29533708?v=3&s=460

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
livere:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
