menu:
    HOME: /

favicon: https://avatars1.githubusercontent.com/u/29533708?v=3&s=460
logo: http://cfile203.uf.daum.net/image/23489C4B5768FA031D7EBA

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
livere:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
